ly around setting up the environment and building the project since you are dealing with Java rather than .NET. Here is the updated YAML for your Java project:

yaml
Copy code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
      - main
    paths:
      - 'app/**'
      - '.github/**'

jobs:
  veracode_agent_sca:
    name: SCA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your desired Java version (e.g., 11, 17, etc.)
          distribution: 'adoptopenjdk'  # You can also use 'temurin' if preferred

      - name: Build the project
        run: |
          ./mvnw clean install  # If using Maven (use './gradlew' for Gradle)
        shell: bash

      - name: Veracode Agent SCA Scan
        run: |
          cd app
          pwd
          export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_TOKEN }}
          export SRCCLR_SKIP_JAVA_MAVEN_INSTALL=true  # Skip Maven install, as we've already built the project
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --update-advisor
        shell: bash
