on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
      - main
    paths:
      - 'app/**'
      - '.github/**'

jobs:
  veracode_agent_sca:
    name: SCA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # #Specify your desired Java version (e.g., 11, 17, etc.)
          distribution: 'temurin'  # #You can also use 'temurin' if preferred

      - name: Install Maven and build the project
        run: |
          # pwd
          # sudo apt-get update
          # sudo apt-get install -y maven
          # pwd
          # mvn -v
          # cd app
          # mvn clean install
          cd app && mvn clean install
          mvn compile -Dcheckstyle.skip=true -e -DskipITs -Dmaven.test.skip=true --fail-fast --nsu -Denforcer.skip=true
          ls -la target
        shell: bash

      - name: Configure Git user
        run: |
          git config --global user.email "dipti.joshi@capgemini.com"
          git config --global user.name "diptjosh"

      
      - name: Veracode Agent SCA Scan
        env:
         SRCCLR_SCM_TYPE: GITHUB
         SRCCLR_SCM_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         PR_ON: "High,Medium"     
         NO_BREAKING_UPDATES: "false"  # Allow breaking updates (false = will not block major version upgrades)
         IGNORE_CLOSE_PRS: "true"
        run: |
          cd app
          pwd
          export SRCCLR_SCM_TYPE="GITHUB"
          export SRCCLR_SCM_TOKEN="${{ secrets.SCM_TOKEN }}"
          export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_TOKEN }}
          export SRCCLR_SKIP_DOTNET_RESTORE=true
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --update-advisor --pull-request
        shell: bash
